Production:
  _templateCategory: *template.category:Zone
  _templateVars:
    Zone: Production
  Source:
    Page: 358
  Oracles:
    - _templateInfo: *template.info:Zone.Area
      _templateTable:
        rolls: *template.rolls:Zone.Area
        content:
          - Airlock or staging area
          - Assembly or processing
          - Cargo bay
          - Equipment storage
          - Exosuit bay
          - Harvesting or mining platform
          - Monitoring or control room
          - Processed goods storage
          - Raw materials storage
          - Scrapyard
          - *result:NewZone
          - *result:NewZoneViaAccess
    - _templateInfo: *template.info:Zone.Feature
      _templateTable:
        rolls: *template.rolls:Zone.Feature
        content:
          - Cargo lifts
          - Control panels
          - Disassembled machinery
          - Elevated walkways
          - Environment suits
          - Ill-fated workers
          - Immense machinery
          - Sealed or locked containers
          - Tools
          - Vats of chemicals or gas
          - Written manifest
          - *result:Descriptor+Focus
    - _templateInfo: *template.info:Zone.Peril
      _templateTable:
        rolls: *template.rolls:Zone.Peril
        content:
          - Claustrophobic spaces
          - Dangerous machinery
          - Disturbing evidence of exploited labor
          - Extreme temperatures
          - Hazardous materials
          - Impending industrial disaster
          - Malfunctioning automation
          - Rivals seek to secure these resources
          - Signs of an unearthed or manufactured threat
          - *result:Action+Theme
          - *result:RollTwice
    - _templateInfo: *template.info:Zone.Opportunity
      _templateTable:
        rolls: *template.rolls:Zone.Opportunity
        content:
          - Helpful vehicle or transport
          - Rare or valuable resource
          - Salvageable materials
          - Useful equipment
          - Valuable cargo
